### ISSUE TITLE
link_echo needs a request timeout

### ISSUE THREAD

**Issue by jfrederickson** [TheSchwa/sibyl#11]
link_echo + HTTP audio streams = very busy bot

**Comment by jfrederickson** [comment]
Just check the content_type for now as a stopgap.

**Comment by abemassry** [comment]
`requests.get` has a timeout on it https://github.com/TheSchwa/sibyl/blob/0735ebd842f77685c408f56f12dc72339c431136/cmds/room.py#L485

**Comment by jfrederickson** [comment]
That timeout doesn't do what you think it does: http://docs.python-requests.org/en/master/user/quickstart/#timeouts

**Comment by TheSchwa** [comment]
Hi Abe :D

Unfortunately Jon is right, that timeout techincally sets two things, `connect` and `read` which don't cover this case.

http://docs.python-requests.org/en/master/user/advanced/#timeouts

I haven't been able to figure out a clean way to timeout actually reading data over the socket without using signals, so content_type is was the best we could come up with.

**Comment by abemassry** [comment]
submitted #34 as a maybe this might work?

**Comment by TheSchwa** [comment]
(1) Check content-type

```
requests.head(URL).headers['Content-Type']
```

(2) As an additional sanity check, check if the results starts with the `<` character, which to my knowledge should be required in all valid html

```
r = requests.get(url, timeout=5)
if not r.text.strip().startswith('<'):
  return
```
