### ISSUE TITLE
matrix: handle sending emote messages

### ISSUE THREAD

**Issue by TheSchwa** [TheSchwa/sibyl#22]
Sibyl now supports sending emote messages. API has changed to reflect this, as `protocol.send()` and `protocol.broadcast()` now only take a single argument, a `Message` object.

The `send()` method in `sibyl_matrix` should check for `mess.get_emote()` and act accordingly.

**Comment by jfrederickson** [comment]
Resolved in https://github.com/TheSchwa/sibyl/commit/e325a4c61f986d0b63952117d9fac797d5d5280d
