### ISSUE TITLE
sibyl_matrix - missing msgtypes

### ISSUE THREAD

**Issue by TheSchwa** [TheSchwa/sibyl#7]
If a user posts an image in a matrix room, the body of the message as seen by sibyl is the filename. Ideally this should be the URL for the file.

**Comment by jfrederickson** [comment]
Partially handled by https://github.com/TheSchwa/sibyl/commit/3f5786683fc8ca2743a90ce7a506c5716920db8b - need to handle other filetypes as well.

**Comment by TheSchwa** [comment]
Current status ([spec ref](http://matrix.org/docs/spec/client_server/r0.2.0.html#m-room-message-msgtypes)):

Implemented = m.text, m.image
Missing = m.emote, m.notice, m.file, m.location, m.video, m.audio

**Comment by jfrederickson** [comment]
Worth noting sibyl should explicitly *not* respond to m.notice events - those are there to prevent bots from responding to each other. It will however need to be able to *send* m.notice events, need to work out how to do that.
